### ISSUE TITLE
IS_BIG_ENDIAN detects if the system IS_LITTLE_ENDIAN

### ISSUE THREAD

**Issue by Alexhuszagh** [ms-numpress/ms-numpress#7]
This doesn't have any implications on the actual code, and it's merely a naming convention, but the `IS_BIG_ENDIAN` detects if the system byteorder is little endian, not big endian.

This is because a big endian system store the most significant bit (MSB) (for example, for a 32-bit integer, `2^31`) as the first bit, while little endian systems store the least significant bit (LSB) as the first bit. 

The following function takes the the leftmost byte, casts it to a char, and checks if that char is 1. On little endian systems, this will succeed (where the bits are `1000000 00000000 ...`, while on big endian systems this will fail (where the bits are `... 0000000 00000001`.

```cpp
const int ONE = 1;
static bool is_big_endian() {
	return *((char*)&(ONE)) == 1;
}
bool IS_BIG_ENDIAN = is_big_endian();
```

The entire issue can be resolved by renaming `IS_BIG_ENDIAN` to `IS_LITTLE_ENDIAN`.

**Comment by fickludd** [comment]
Hi @Alexhuszagh, and thank you for taking the time to point this out! A small mix-up indeed, you are correct in that the bool really flags for LITTLE endianess. Fixed in https://github.com/ms-numpress/ms-numpress/commit/188fce4be868bfe8a9a53e35954583993646eb73. 

That said, the endianess denotes the order of _bytes_ rather that bits, just a reminder =).
